/** Todos los `data-testid` que usan los E2E, en un solo lugar (CLAUDE.md §11). */
export const ids = {
  inicio: { dividir: "ir-dividir", grupo: (id: string) => `demo-grupo-${id}` },
  dividir: { resumen: "dividir-resumen", frase: "frase-gasto", enviarFrase: "frase-gasto-enviar", monto: "dividir-monto", confirmar: "dividir-confirmar", aviso: "dividir-aviso", guardados: "dividir-guardados" },
  modos: {
    otras: "otras-formas",
    modo: (m: string) => `modo-${m}`,
    valor: (id: string) => `valor-${id}`,
    estado: "dividir-estado",
    sinAsignar: "dividir-sin-asignar",
    completar: "completar-porcentaje",
    absorber: (n: number) => `sin-asignar-absorber-${n}`,
    productoNombre: "producto-nombre",
    productoPrecio: "producto-precio",
    productoQuien: (id: string) => `producto-quien-${id}`,
    productoAgregar: "producto-agregar",
    parte: (id: string) => `parte-${id}`,
    comoPagarse: "como-pagarse",
  },
  inicio_resumen: {
    debes: "inicio-debes",
    teDeben: "inicio-te-deben",
    texto: "inicio-resumen-texto",
    teToca: "inicio-te-toca",
    verTodas: "inicio-ver-todas",
    estado: "inicio-estado",
    probar: (id: string) => `inicio-probar-${id}`,
  },
  cuenta: {
    fila: (id: string) => `cuenta-${id}`,
    monto: (id: string) => `cuenta-monto-${id}`,
    pagar: (id: string) => `cuenta-pagar-${id}`,
    cancelar: (id: string) => `cuenta-cancelar-${id}`,
    pendiente: (id: string) => `cuenta-pendiente-${id}`,
    disputa: (id: string) => `cuenta-disputa-${id}`,
  },
  hoja: { raiz: "hoja-pago", monto: "hoja-monto", confirmar: "hoja-confirmar", cerrar: "hoja-cerrar", error: "hoja-error" },
  toast: { raiz: "toast-pago", deshacer: "toast-deshacer" },
  nav: { inicio: "nav-inicio", dividir: "nav-dividir", grupos: "nav-grupos", yo: "nav-yo", pendientes: "nav-pendientes" },
  pagos: {
    porConfirmar: "por-confirmar",
    porRevisar: "por-revisar",
    confirmar: '[data-testid^="confirmar-"]',
    rechazar: '[data-testid^="rechazar-"]',
    aprobar: '[data-testid^="aprobar-"]',
    avisos: "avisos-pago",
    avisoXp: '[data-testid^="aviso-xp-"]',
    avisoOk: '[data-testid^="aviso-ok-"]',
    avisoCancelar: '[data-testid^="aviso-cancelar-"]',
    reiniciar: "reiniciar-demo",
    misCuentas: "mis-cuentas",
    plan: (d: string, a: string) => `plan-${d}-${a}`,
    planPagar: (d: string, a: string) => `plan-pagar-${d}-${a}`,
    todasLasDeudas: "todas-las-deudas",
    herramientas: "herramientas-demo",
  },
  perfil: { nombre: "perfil-nombre", guardar: "perfil-guardar", error: "perfil-error", guardado: "perfil-guardado", actual: "perfil-nombre-actual", base: (b: string) => `perfil-base-${b}` },
  inicio_hero: { raiz: "inicio-hero", globo: "inicio-globo", camino: "inicio-camino", toque: "inicio-personaje-toque" },
  revelacion: { raiz: "revelacion", xp: "revelacion-xp", nivel: "revelacion-nivel", estado: "revelacion-estado", ok: "revelacion-ok" },
  yo: { heroe: "perfil-heroe", meta: "perfil-meta", skinActiva: "skin-activa", probar: (s: string) => `skin-probar-${s}`, grupo: "perfil-grupo" },
  confirmar: { total: "ia-total", confirmar: "ia-confirmar", guardado: "ia-guardado", resultado: "ia-resultado" },
  personaje: { raiz: "personaje", canvas: "personaje-canvas", respaldo: "personaje-respaldo", estado: (e: string) => `estado-${e}`, base: (b: string) => `base-${b}`, skin: (s: string) => `skin-${s}`, nivel: "nivel", festejar: "festejar", celebraciones: "data-celebraciones" },
  saldar: { estado: "mi-estado", error: "pagar-error" },
} as const;
